#Build Steps
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-db:latest',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-db:$TAG_NAME',
        '.']
      waitFor: ['-']
      dir: 'db'
      id: 'wordpress-child-db-latest'

    - name: 'gcr.io/cloud-builders/docker'
      args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-elasticsearch:latest',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-elasticsearch:$TAG_NAME',
        '.']
      waitFor: ['-']
      dir: 'elasticsearch'
      id: 'wordpress-child-elasticsearch-latest'

    - name: 'gcr.io/cloud-builders/docker'
      args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-wordpress:latest',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-wordpress:$TAG_NAME',
        '.']
      waitFor: ['-']
      dir: 'wordpress'
      id: 'wordpress-child-wordpress-child-latest'

    - name: 'gcr.io/cloud-builders/docker'
      args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-nginx:latest',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-nginx:$TAG_NAME',
        '.']
      waitFor: ['-']
      dir: 'nginx'
      id: 'wordpress-child-nginx-latest'

    - name: 'gcr.io/cloud-builders/docker'
      args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-redis:latest',
        '-t', 'gcr.io/$PROJECT_ID/wordpress-child-redis:$TAG_NAME',
        '.']
      waitFor: ['-']
      dir: 'redis'
      id: 'wordpress-child-redis-latest'


# Images for GCB to check for:
images:
    # Tagged with LATEST
    - 'gcr.io/$PROJECT_ID/wordpress-child-db'
    - 'gcr.io/$PROJECT_ID/wordpress-child-elasticsearch'
    - 'gcr.io/$PROJECT_ID/wordpress-child-wordpress'
    - 'gcr.io/$PROJECT_ID/wordpress-child-nginx'
    - 'gcr.io/$PROJECT_ID/wordpress-child-redis'

    # Tagged with Git Tag
    - 'gcr.io/$PROJECT_ID/wordpress-child-db:$TAG_NAME'
    - 'gcr.io/$PROJECT_ID/wordpress-child-elasticsearch:$TAG_NAME'
    - 'gcr.io/$PROJECT_ID/wordpress-child-wordpress:$TAG_NAME'
    - 'gcr.io/$PROJECT_ID/wordpress-child-nginx:$TAG_NAME'
    - 'gcr.io/$PROJECT_ID/wordpress-child-redis:$TAG_NAME'
