version: '2'

services:
    #db:
    #    build:
    #        context: ./db/
    #        dockerfile: Dockerfile
    #    env_file:
    #        - ./db/db.env
    #    environment:
    #        - "MYSQL_ROOT_PASSWORD=jellyfish"
    #    hostname: db
    #    networks:
    #        - wpnet
    #    restart: always
    #    volumes:
    #        - "./db/db_data:/var/lib/mysql"

    wordpress:
        build:
            context: ./wordpress/
            dockerfile: Dockerfile
        #depends_on:
            #- db
        env_file:
            - ./wordpress/wordpress.env
            - ./host.env
        environment:
            - "WORDPRESS_ADMIN_PASSWORD=password"
            - "db=172.17.0.1"
        hostname: wordpress
        networks:
            - wpnet
        restart: always
        volumes:
            - "./wordpress/wordpress-entrypoint.sh:/usr/local/bin/wordpress-entrypoint.sh"
            - "./wordpress/wp-config.php:/var/www/html/wp-config.php"
            - "./wordpress/db-config.php:/var/www/html/db-config.php"
            - "./wordpress/wp-content:/var/www/html/wp-content"
            - "./wordpress/uploads:/var/www/html/wp-content/uploads"
            - "./wordpress/.htaccess:/var/www/html/.htaccess"
            - "./logs/wordpress/php-error.log:/var/log/php-error.log"
        working_dir: /var/www/html

    nginx:
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        hostname: nginx
        networks:
            - wpnet
        ports:
            - "8080:8080"
            #- "443:443"
        restart: always
        volumes:
            - "./logs/nginx:/var/log/nginx"
            - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
        volumes_from:
            - wordpress
    varnish: 
        build: 
            context: ./varnish
            dockerfile: Dockerfile
        depends_on:
            - nginx
        env_file: 
            - ./varnish/varnish.env   
        hostname: varnish
        networks:
            - wpnet
        ports: 
            - "80:6081"
        restart: always
        

     

    # redis:
    #     build:
    #         context: ./redis/
    #         dockerfile: Dockerfile
    #     depends_on:
    #         - wordpress
    #     env_file:
    #         - ./wordpress/wordpress.env
    #     hostname: redis
    #     networks:
    #         - wpnet
    #     restart: always
    #     volumes:
    #         - "./redis/default.conf:/usr/local/etc/redis/redis.conf"

    # memcached:
    #     image: memcached
    #       env_file:
    #           - ./global.env
    #     hostname: memcached
    #     networks:
    #         - wpnet
    #     restart: always

    # elasticsearch:
    #     build:
    #         context: ./elasticsearch/
    #         dockerfile: Dockerfile
    #     depends_on:
    #         - wordpress
    #     hostname: elasticsearch
    #     ports:
    #         - "127.0.0.1:9200:9200"
    #     volumes:
    #         - "./elasticsearch/data:/usr/share/elasticsearch/data"
    #         - "./elasticsearch/plugins:/usr/share/elasticsearch/plugins"
    #     networks:
    #         - wpnet
    #     restart: always

networks:
    wpnet:
        driver: bridge
