version: '2'

services:

    wordpress:
        build:
            context: ./wordpress/
            dockerfile: Dockerfile
     #   depends_on:
     #       - db
        env_file:
            - ./wordpress/wordpress.env
            - ./host.env
        environment:
            - "WORDPRESS_ADMIN_PASSWORD=ek4aexi4Kanigh6"
        hostname: wordpress
        networks:
            - wpnet
        restart: always
        volumes:
            - "./wordpress/wordpress-entrypoint.sh:/usr/local/bin/wordpress-entrypoint.sh"
            - "./wordpress/wp-config.php:/var/www/html/wp-config.php"
            - "./wordpress/db-config.php:/var/www/html/db-config.php"
            - "./wordpress/wp-content:/var/www/html/wp-content"
            - "./wordpress/uploads:/var/www/html/wp-content/uploads"
            - "./wordpress/.htaccess:/var/www/html/.htaccess"
            - "./logs/wordpress/php-error.log:/var/log/php-error.log"
        working_dir: /var/www/html

    nginx:
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        hostname: nginx
        networks:
            - wpnet
        ports:
            - "80:80"
            #- "443:443"
        restart: always
        volumes:
            - "./logs/nginx:/var/log/nginx"
            - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
        volumes_from:
            - wordpress

networks:
    wpnet:
        driver: bridge
