apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache
  namespace: production
  labels:
    name: cache
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - fsc
  nfs:
    path: /var/nfsroot
    server: null
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: production
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
     requests:
       storage: 50Gi
  selector:
    matchLabels:
      name: cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads
  namespace: production
  labels:
    name: uploads
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
  nfs:
    path: /var/uploads
    server: null
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  namespace: production
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
     requests:
       storage: 50Gi
  selector:
    matchLabels:
      name: uploads
